create table PLAYER (
  PLAYERID integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 0),
);

create table SPACE_WORLD(
  worldid integer,
  startstep integer,
  startsegment integer
);

create table SEGMENT(
    worldid integer,
    segmentid integer,
    naturalorder integer,
    content varchar(300)
);

create table SEGMENT_DOOR (
  segmentdoorid integer,
  worldid integer,
  sourcesegment integer,
  targetsegment integer,
  sourcestep integer,
  targetstep integer
);