sudo: required
dist: trusty

language: java

jdk:
  - oraclejdk8

notifications:
  email: false
  slack: the-space-game:d7oegXy04GWkYpx1FexPbuDW


# space-client build

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
# Matrix failure enabled for https://github.com/TheLarkInn/LazyParseWebpackPlugin/issues/6
matrix:
  fast_finish: true
  allow_failures:
  - node_js: "4"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3


# overall space build:
# 1) space-client
# 2) space-common
# 3) space-server
# -> space-server bundles client files in war-file
# overall build artifact: space-server-all.war

script:
  - cd space-client # go to space-client and start build via npm
  - npm install
  - npm run lint
  - npm test
  - npm run build:prod
  - npm run server:prod:ci &
  - sleep 3
  - npm run e2e

  - cd ../ # back to root folder
  - ./gradlew stage # start build of space-common and space-server, building a space-all fat-jar including the client
