sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
# Matrix failure enabled for https://github.com/TheLarkInn/LazyParseWebpackPlugin/issues/6
matrix:
  fast_finish: true
  allow_failures:
  - node_js: "4"

language: java

jdk:
  - oraclejdk8
notifications:
  email: false
  slack: the-space-game:d7oegXy04GWkYpx1FexPbuDW
